apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: seqctl

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: golemnetwork/seqctl
    newTag: latest

configMapGenerator:
  - name: seqctl-config
    behavior: replace
    files:
      - config.toml
