apiVersion: v1
kind: ServiceAccount
metadata:
  name: seqctl
  namespace: seqctl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seqctl
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/proxy"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: seqctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seqctl
subjects:
  - kind: ServiceAccount
    name: seqctl
    namespace: seqctl
