name: Nix Fmt

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nix-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run nix fmt
        run: nix fmt -- --ci
